name: tests

on: push

env:
  PGPASSWORD : 'devPass'

jobs:
  container-job:
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: devPass
          POSTGRES_USER: postgres
          POSTGRES_DB: coinrocketdb
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5433 on service container to the host
          - 5433:5432

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Install sudo package
        run: apt update && apt install sudo

      - name: Install postgresql-client
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client

      - name: Create database
        run: |
          sudo -u postgres psql -c 'create database coinrocketdb;'
        env:
          POSTGRES_PASSWORD: devPass
          POSTGRES_PORT: 5433

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test with Maven
        run: mvn -B test --file pom.xml
